### ISSUE TITLE
Get json string posted.

### ISSUE THREAD

**Issue by glennpierce** [iron/params#36]
How can I post JSON data to an irom method and just get back the JSON string or convert the Map I get to a string ?

I have tried to send with JSON.stringify.
That causes iron to always give the error

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPath'

$.ajax({
        type: "POST",
        url: "/pipeline_save/" + pipeline.save,
        data: JSON.stringify(data),
        dataType: String
      });

I can send json as an object 

ie
$.ajax({
        type: "POST",
        url: "/pipeline_save/" + pipeline.save,
        data: data,
        dataType: String
      });

In that case I get a map back. 
How can I get the original string ?

the rust code is

let data = request.get_ref::<Params>().unwrap();
println!("{:?}", data);

Thanks

**Comment by SkylerLipthay** [comment]
Well, I can't be sure exactly why you're getting an `InvalidPath` error because the Rust code you posted is definitely incomplete... But I would say that because you are just POSTing with a body that is just a simple string, you shouldn't be using the `Params` plugin at all. For this case, I would use [`body-parser`](https://github.com/iron/body-parser) and `let body = req.get::<bodyparser::Raw>();` to get the raw body string.

**Comment by glennpierce** [comment]
Yep that method works.
Thanks
